on:
  push:
  pull_request:
  workflow_dispatch:
env:
  SVD2ADA_COMPILE_CHECKS: enabled
  SVD2ADA_RUNTIME_CHECKS: enabled
  SVD2ADA_STYLE_CHECKS: enabled
  SVD2ADA_CONTRACTS: enabled
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: alire-project/setup-alire@v3
        with:
          toolchain: gnat_native${{ matrix.gnat_version }} gprbuild${{ matrix.gprbuild_version }} --disable-assistant
      - run: alr build
